name: ssl
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _ipyw_jlab_nb_ext_conf=0.1.0
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alabaster=0.7.12
  - anaconda=2021.11
  - anaconda-client=1.9.0
  - anaconda-navigator=2.1.1
  - anaconda-project=0.10.1
  - anyio=2.2.0
  - appdirs=1.4.4
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - arrow=0.13.1
  - asn1crypto=1.4.0
  - astroid=2.6.6
  - astropy=4.3.1
  - async_generator=1.10
  - atomicwrites=1.4.0
  - attrs=21.2.0
  - autopep8=1.5.7
  - babel=2.9.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - backports.shutil_get_terminal_size=1.0.0
  - backports.tempfile=1.0
  - backports.weakref=1.0.post1
  - beautifulsoup4=4.10.0
  - binaryornot=0.4.4
  - bitarray=2.3.0
  - bkcharts=0.2
  - black=19.10b0
  - blas=1.0
  - bleach=4.0.0
  - blosc=1.21.0
  - bokeh=2.4.1
  - boto=2.49.0
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cached-property=1.5.2
  - cairo=1.16.0
  - certifi=2021.10.8
  - cffi=1.14.6
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - cloudpickle=2.0.0
  - clyent=1.2.2
  - colorama=0.4.4
  - conda=4.11.0
  - conda-build=3.21.5
  - conda-content-trust=0.1.1
  - conda-env=2.6.0
  - conda-pack=0.6.0
  - conda-package-handling=1.7.3
  - conda-repo-cli=1.0.4
  - conda-token=0.3.0
  - conda-verify=3.4.2
  - contextlib2=0.6.0.post1
  - cookiecutter=1.7.2
  - cryptography=3.4.8
  - cudatoolkit=11.3.1
  - curl=7.78.0
  - cycler=0.10.0
  - cython=0.29.24
  - cytoolz=0.11.0
  - daal4py=2021.3.0
  - dal=2021.3.0
  - dask=2021.10.0
  - dask-core=2021.10.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - diff-match-patch=20200713
  - distributed=2021.10.0
  - docutils=0.17.1
  - efficientnet-pytorch=0.7.1
  - einops=0.4.0
  - entrypoints=0.3
  - et_xmlfile=1.1.0
  - expat=2.4.1
  - fastcache=1.1.0
  - ffmpeg=4.3
  - filelock=3.3.1
  - flake8=3.9.2
  - flask=1.1.2
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - fribidi=1.0.10
  - fsspec=2021.8.1
  - future=0.18.2
  - get_terminal_size=1.0.0
  - gevent=21.8.0
  - giflib=5.2.1
  - glib=2.69.1
  - glob2=0.7
  - gmp=6.2.1
  - gmpy2=2.0.8
  - gnutls=3.6.15
  - graphite2=1.3.14
  - greenlet=1.1.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=3.3.0
  - harfbuzz=2.8.1
  - hdf5=1.10.6
  - heapdict=1.0.1
  - html5lib=1.1
  - icu=58.2
  - idna=3.2
  - imagecodecs=2021.8.26
  - imageio=2.9.0
  - imagesize=1.2.0
  - importlib-metadata=4.8.1
  - importlib_metadata=4.8.1
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - intervaltree=3.1.0
  - ipykernel=6.4.1
  - ipython=7.29.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - isort=5.9.3
  - itsdangerous=2.0.1
  - jbig=2.1
  - jdcal=1.4.1
  - jedi=0.18.0
  - jeepney=0.7.1
  - jinja2=2.11.3
  - jinja2-time=0.2.0
  - joblib=1.1.0
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.8.1
  - jupyter_server=1.4.1
  - jupyterlab=3.2.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.8.2
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=23.1.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lazy-object-proxy=1.6.0
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=3.0
  - libaec=1.0.4
  - libarchive=3.4.2
  - libcurl=7.78.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - liblief=0.10.1
  - libllvm11=11.1.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - libxslt=1.1.34
  - libzopfli=1.0.3
  - llvmlite=0.37.0
  - locket=0.2.1
  - lxml=4.6.3
  - lz4-c=1.9.3
  - lzo=2.10
  - markupsafe=1.1.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mock=4.0.3
  - more-itertools=8.10.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpich=3.3.2
  - mpmath=1.2.1
  - msgpack-python=1.0.2
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mypy_extensions=0.4.3
  - navigator-updater=0.2.1
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - nettle=3.7.3
  - networkx=2.6.3
  - nltk=3.6.5
  - nose=1.3.7
  - notebook=6.4.5
  - numba=0.54.1
  - numexpr=2.7.3
  - numpy=1.20.3
  - numpy-base=1.20.3
  - numpydoc=1.1.0
  - olefile=0.46
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openpyxl=3.0.9
  - openssl=1.1.1l
  - packaging=21.0
  - pandas=1.3.4
  - pandocfilters=1.4.3
  - pango=1.45.3
  - parso=0.8.2
  - partd=1.2.0
  - patchelf=0.13
  - path=16.0.0
  - path.py=12.5.0
  - pathlib2=2.3.6
  - pathspec=0.7.0
  - patsy=0.5.2
  - pcre=8.45
  - pep8=1.7.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - pixman=0.40.0
  - pkginfo=1.7.1
  - pluggy=0.13.1
  - ply=3.11
  - poyo=0.5.0
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.20
  - prompt_toolkit=3.0.20
  - protobuf=3.15.8
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py=1.10.0
  - py-lief=0.10.1
  - pycodestyle=2.7.0
  - pycosat=0.6.3
  - pycparser=2.20
  - pycurl=7.44.1
  - pydocstyle=6.1.1
  - pyerfa=2.0.0
  - pyflakes=2.3.1
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pylint=2.9.6
  - pyls-spyder=0.4.0
  - pyodbc=4.0.31
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - pytables=3.6.1
  - pytest=6.2.4
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python-lsp-black=1.0.0
  - python-lsp-jsonrpc=1.0.0
  - python-lsp-server=1.2.4
  - python-slugify=5.0.2
  - python_abi=3.9
  - pytorch=1.10.2
  - pytorch-mutex=1.0
  - pytz=2021.3
  - pywavelets=1.1.1
  - pyxdg=0.27
  - pyyaml=6.0
  - pyzmq=22.2.1
  - qdarkstyle=3.0.2
  - qstylizer=0.1.10
  - qt=5.9.7
  - qtawesome=1.0.2
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - regex=2021.8.3
  - requests=2.26.0
  - ripgrep=12.1.1
  - rope=0.19.0
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scikit-image=0.18.3
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.3.0
  - scipy=1.7.1
  - seaborn=0.11.2
  - secretstorage=3.3.1
  - send2trash=1.8.0
  - setuptools=58.0.4
  - simplegeneric=0.8.1
  - singledispatch=3.7.0
  - sip=4.19.13
  - six=1.16.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - snowballstemmer=2.1.0
  - sortedcollections=2.1.0
  - sortedcontainers=2.4.0
  - soupsieve=2.2.1
  - sphinx=4.2.0
  - sphinxcontrib=1.0
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - sphinxcontrib-websupport=1.2.4
  - spyder=5.1.5
  - spyder-kernels=2.1.3
  - sqlalchemy=1.4.22
  - sqlite=3.36.0
  - statsmodels=0.12.2
  - sympy=1.9
  - tbb=2021.4.0
  - tbb4py=2021.4.0
  - tblib=1.7.0
  - tensorboardx=2.4
  - terminado=0.9.4
  - testpath=0.5.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=2.2.0
  - three-merge=0.1.1
  - tifffile=2021.7.2
  - timm=0.4.12
  - tinycss=0.4
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - torchaudio=0.10.2
  - torchvision=0.11.3
  - tornado=6.1
  - tqdm=4.62.3
  - traitlets=5.1.0
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - ujson=4.0.2
  - unicodecsv=0.14.1
  - unidecode=1.2.0
  - unixodbc=2.3.9
  - urllib3=1.26.7
  - watchdog=2.1.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.0
  - whichcraft=0.6.1
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - wurlitzer=2.1.1
  - xlrd=2.0.1
  - xlsxwriter=3.0.1
  - xlwt=1.3.0
  - xmltodict=0.12.0
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - yapf=0.31.0
  - zeromq=4.3.4
  - zfp=0.5.5
  - zict=2.0.0
  - zipp=3.6.0
  - zlib=1.2.11
  - zope=1.0
  - zope.event=4.5.0
  - zope.interface=5.4.0
  - zstd=1.4.9
  - pip:
    - opencv-python==4.5.5.62
